export const categorieConstant={
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCES:'GET_CATEGORY_SUCCES',
    GET_CATEGORY_FAILURE:'GET_CATEGORY_FAILURE',
    UPDATE_CATEGORY_SUCCES:'UPDATE_CATEGORY_SUCCES',
}
export const ProductByslugConstant={
   PRODUCT_BY_SLUG_SUCEES:'PRODUCT_BY_SLUG_SUCEES',
}
export const ProductPageConstant={
    PRODUCT_GET_PAGE_REQUEST:'PRODUCT_GET_PAGE_REQUEST',
    PRODUCT_GET_PAGE_SUCCES:'PRODUCT_GET_PAGE_SUCCES',
    PRODUCT_GET_PAGE_FAILURE:'PRODUCT_GET_PAGE_FAILURE',
}
export const ProductIdConstant={
    PRODUCT_ID_GET_REQUEST:'PRODUCT_ID_GET_REQUEST',
    PRODUCT_ID_GET_SUCCES:'PRODUCT_ID_GET_SUCCES',
    PRODUCT_ID_GET_FAILURE:'PRODUCT_ID_GET_FAILURE',
}
export  const  authConstant={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCES:'LOGIN_SUCCES',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCES:'LOGOUT_SUCCES',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'

}
export  const  userConstant={
    USER_REGISTER_REQUEST:' USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCES:' USER_REGISTER_SUCCES',
    USER_REGISTER_FAILURE:' USER_REGISTER_FAILURE'
}
export const cartConstant={
    Add_To_Cart:"Add_To_Cart",
    RESET_CART:"RESET_CART"
}
export const AddressConstant={
    GET_ADDRESS_REQUEST:"GET_ADDRESS_REQUEST",
    GET_ADDRESS_SUCCES:"GET_ADDRESS_SUCCES",
    GET_ADDRESS_FAILURE:"GET_ADDRESS_FAILURE",
    ADD_ADDRESS_REQUEST:"ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_SUCCES:"ADD_ADDRESS_SUCCES",
    ADD_ADDRESS_FAILURE:"ADD_ADDRESS_FAILURE",
}
export const OrderConstant={
    GET_ORDER_REQUEST:"GET_ORDER_REQUEST",
    GET_ORDER_SUCCES:"GET_ORDER_SUCCES",
    GET_ORDER_FAILURE:"GET_ORDER_FAILURE",
    ADD_ORDER_REQUEST:"ADD_ORDER_REQUEST",
    ADD_ORDER_SUCCES:"ADD_ORDER_SUCCES",
    ADD_ORDER_FAILURE:"ADD_ORDER_FAILURE",
    GET_ORDER_BYID_REQUEST:'GET_ORDER_BYID_REQUEST',
    GET_ORDER_BYID_SUCCES:'GET_ORDER_BYID_SUCCES',
    GET_ORDER_BYID_FAILURE:'GET_ORDER_BYID_FAILURE',
}