export  const  authConstant={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCES:'LOGIN_SUCCES',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCES:'LOGOUT_SUCCES',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'

}
export  const  userConstant={
    USER_REGISTER_REQUEST:' USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCES:' USER_REGISTER_SUCCES',
    USER_REGISTER_FAILURE:' USER_REGISTER_FAILURE'
}
export  const  CategorieConstant={
    //get Category
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCES:' GET_CATEGORY_SUCCES',
    GET_CATEGORY_FAILURE:'GET_CATEGORY_FAILURE',
    //add category
    ADD_CATEGORY_REQUEST:' ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCES:' ADD_CATEGORY_SUCCES',
    ADD_CATEGORY_FAILURE:' ADD_CATEGORY_FALURE',
    //update category
    UPDATE_CATEGORY_REQUEST:'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCES:'UPDATE_CATEGORY_SUCCES',
    UPDATE_CATEGORY_FAILURE:'UPDATE_CATEGORY_FAILURE',
    //delete category
    DELETE_CATEGORY_REQUEST:'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCES:'DELETE_CATEGORY_SUCCES',
    DELETE_CATEGORY_FAILURE:'DELETE_CATEGORY_FAILURE'
}
export  const  ProductConstant={
    GET_PRODUCT_REQUEST:'  GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCES:'   GET_PRODUCT_SUCCES',
    GET_PRODUCT_FAILURE:'  GET_PRODUCT_FAILURE',
    ADD_PRODUCT_SUCCES:'   ADD_PRODUCT_SUCCES',
}
export const PageConstant={
    ADD_PAGE_REQUEST:'ADD_PAGE_REQUEST',
    ADD_PAGE_SUCCES:'ADD_PAGE_SUCCES',
    ADD_PAGE_FAILURE:'ADD_PAGE_FAILURE'
}
export const orderConstant={
    GET_ORDER_REQUEST:' GET_ORDER_REQUEST',
    GET_ORDER_SUCCES:' GET_ORDER_SUCCES',
    GET_ORDER_FAILURE:' GET_ORDER_FAILURE', 
}